services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app       
    depends_on:
      - geoutils_app
    environment:
      - PYTHONUNBUFFERED=1

  geoutils_app:
    image: nvidia/cuda:11.2-base   
    container_name: geoutils_app
    volumes:
      - geoutils_data:/app/ 


volumes:
  geoutils_data:
    driver: local
